export { default as AeroWindowBar } from './AeroWindowBar';
export { default as Header } from './Header';
export { default as About } from './About';
export { default as Experience } from './Experience';
export { default as Education } from './Education';
export { default as Contact } from './Contact';
export { default as Footer } from './Footer';
export { default as XPStartButton } from './XPStartButton';
export { default as XPStartMenu } from './XPStartMenu'; 